# Generated by Django 4.2.2 on 2023-08-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the airport", max_length=30),
                ),
                (
                    "address",
                    models.TextField(help_text="Airport address", max_length=200),
                ),
                ("contact", models.TextField(help_text="Phone no.", max_length=200)),
                (
                    "types_of_traffic_permitted",
                    models.CharField(
                        choices=[("VFR", "VFR"), ("IFR", "IFR")],
                        help_text="Type of traffic permission - one type or two types",
                        max_length=3,
                    ),
                ),
                ("radio", models.FloatField(help_text="Radio frequency")),
                ("elevation", models.IntegerField(help_text="Airport elevation in ft")),
                (
                    "co_ordinates",
                    models.TextField(
                        help_text="ARP - coordinates and site at AD", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Other information about Information", max_length=300
                    ),
                ),
                ("length", models.IntegerField(help_text="Airport length")),
                ("width", models.IntegerField(help_text="Airport width")),
                (
                    "square_meters",
                    models.IntegerField(help_text="Airport square meters"),
                ),
                (
                    "AIP",
                    models.FileField(
                        blank=True,
                        help_text="AIP – Aeronautical Information Publication",
                        null=True,
                        upload_to="uploads/AIP",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Runway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the Runway", max_length=30),
                ),
                ("length", models.IntegerField(help_text="Runway length in meters")),
                ("width", models.IntegerField(help_text="Runway width in meters")),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("ASP", "Asphalt"),
                            ("BIT", "Bituminous asphalt or tarmac"),
                            ("CLA", "Clay"),
                            ("COM", "Composite"),
                            ("CON", "Concrete"),
                            ("COP", "Composite"),
                            ("COR", "Coral - fine crushed coral reef structures"),
                            ("GRE", "Graded or rolled earth, grass on graded earth"),
                            ("GRS", "Grass or earth not graded or rolled"),
                            ("GVL", "Gravel"),
                            ("ICE", "Ice"),
                            ("LAT", "Laterite"),
                            ("MAC", "Macadam"),
                            (
                                "PEM",
                                "Partially concrete, asphalt or bitumen-bound macadam",
                            ),
                            ("PER", "Permanent surface, details unknown"),
                            (
                                "PSP",
                                "Marston Matting (derived from pierced/perforated steel planking",
                            ),
                            ("SAN", "Sand"),
                            ("SMT", "Sommerfeld Tracking"),
                            ("SNO", "Snow"),
                            ("U", "Unknown surface"),
                            ("WAT", "Water"),
                        ],
                        help_text="Runway type of surface. From tuple SURFACE",
                        max_length=100,
                    ),
                ),
                (
                    "light",
                    models.BooleanField(
                        help_text="Installed lighting on a Runway - Yes/No"
                    ),
                ),
                (
                    "markings",
                    models.BooleanField(help_text="Marks on a Runway - Yes/No"),
                ),
                (
                    "TORA",
                    models.IntegerField(help_text="Take-off run available in meters"),
                ),
                (
                    "LDA",
                    models.IntegerField(
                        help_text="Landing distance available in meters"
                    ),
                ),
                ("CWY", models.IntegerField(help_text="Clearway in meters")),
                ("SWY", models.IntegerField(help_text="Stopway in meters")),
                (
                    "airport_id",
                    models.ForeignKey(
                        help_text="Airport ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutsideAircraftStand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the outside stand", max_length=30
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        choices=[
                            ("ASP", "Asphalt"),
                            ("BIT", "Bituminous asphalt or tarmac"),
                            ("CLA", "Clay"),
                            ("COM", "Composite"),
                            ("CON", "Concrete"),
                            ("COP", "Composite"),
                            ("COR", "Coral - fine crushed coral reef structures"),
                            ("GRE", "Graded or rolled earth, grass on graded earth"),
                            ("GRS", "Grass or earth not graded or rolled"),
                            ("GVL", "Gravel"),
                            ("ICE", "Ice"),
                            ("LAT", "Laterite"),
                            ("MAC", "Macadam"),
                            (
                                "PEM",
                                "Partially concrete, asphalt or bitumen-bound macadam",
                            ),
                            ("PER", "Permanent surface, details unknown"),
                            (
                                "PSP",
                                "Marston Matting (derived from pierced/perforated steel planking",
                            ),
                            ("SAN", "Sand"),
                            ("SMT", "Sommerfeld Tracking"),
                            ("SNO", "Snow"),
                            ("U", "Unknown surface"),
                            ("WAT", "Water"),
                        ],
                        help_text="Stand type of surface. From tuple SURFACE",
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        help_text="Runway type of surface. From tuple AIRCRAFT_STAND_SIZE",
                        max_length=100,
                    ),
                ),
                (
                    "taken",
                    models.BooleanField(help_text="Information if this stand is taken"),
                ),
                (
                    "airport_id",
                    models.ForeignKey(
                        help_text="Airport ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hangar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the hangar", max_length=30),
                ),
                (
                    "hangar_height",
                    models.FloatField(help_text="Hangar height in stand space"),
                ),
                (
                    "hangar_wight",
                    models.FloatField(help_text="Hangar wight in stand space"),
                ),
                ("doors_height", models.FloatField(help_text="Hangars doors height")),
                ("doors_wight", models.FloatField(help_text="Hangars doors wight")),
                (
                    "small_stands_no",
                    models.IntegerField(
                        help_text="How many small stands are in Hangar"
                    ),
                ),
                (
                    "small_stands_taken",
                    models.IntegerField(
                        help_text="How many small stands are in Hangar are taken"
                    ),
                ),
                (
                    "airport_id",
                    models.ForeignKey(
                        help_text="Airport ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airport",
                    ),
                ),
            ],
        ),
    ]
