# Generated by Django 4.2.2 on 2023-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the airport", max_length=30),
                ),
                ("address", models.TextField(max_length=200)),
                ("contact", models.TextField(max_length=200)),
                ("types_of_traffic_permitted", models.TextField(max_length=200)),
                ("radio", models.FloatField()),
                ("elevation", models.IntegerField()),
                ("co_ordinates", models.TextField(max_length=200)),
                ("description", models.TextField(max_length=300)),
                ("length", models.IntegerField()),
                ("width", models.IntegerField()),
                ("square_meters", models.IntegerField()),
            ],
        ),
    ]
