# Generated by Django 4.2.2 on 2023-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_airport_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="city",
            field=models.CharField(help_text="Airport city", max_length=30),
        ),
    ]
