# Generated by Django 4.2.2 on 2023-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_runway_length_alter_runway_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runway",
            name="CWY",
            field=models.FloatField(help_text="Clearway in meters"),
        ),
        migrations.AlterField(
            model_name="runway",
            name="LDA",
            field=models.FloatField(help_text="Landing distance available in meters"),
        ),
        migrations.AlterField(
            model_name="runway",
            name="SWY",
            field=models.FloatField(help_text="Stopway in meters"),
        ),
        migrations.AlterField(
            model_name="runway",
            name="TORA",
            field=models.FloatField(help_text="Take-off run available in meters"),
        ),
    ]
