# Generated by Django 4.2.2 on 2023-10-30 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_outsideaircraftstand_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airport",
            old_name="company_id",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="hangar",
            old_name="airport_id",
            new_name="airport",
        ),
        migrations.RenameField(
            model_name="outsideaircraftstand",
            old_name="airport_id",
            new_name="airport",
        ),
        migrations.RenameField(
            model_name="runway",
            old_name="airport_id",
            new_name="airport",
        ),
    ]
