# Generated by Django 4.2.2 on 2023-11-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_rename_company_id_department_company"),
        ("airport", "0008_rename_company_id_airport_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="company",
            field=models.ForeignKey(
                help_text="Company ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airports",
                to="organization.company",
            ),
        ),
    ]
