# Generated by Django 4.2.2 on 2023-11-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_rename_company_id_department_company"),
        ("users", "0003_rename_company_id_customuser_company_delete_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.company",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Airport office"),
                    ("control", "Flight control"),
                    ("mechanic", "Aircraft machinery"),
                    ("cleaning", "Aircraft cleaning department"),
                    ("air", "aircraft Crew"),
                    ("IT", "IT department"),
                ],
                help_text="Users work department, model department in organization app",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="job_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ceo", "CEO"),
                    ("manager", "Manager"),
                    ("worker", "Worker"),
                    ("specialist", "Specialist"),
                    ("pilot", "Aircraft pilot"),
                ],
                help_text="Users work job title, model worker in organization app",
                max_length=20,
                null=True,
            ),
        ),
    ]
