# Generated by Django 4.2.2 on 2023-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_company_alter_customuser_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="job_position",
            field=models.CharField(
                choices=[
                    ("ceo", "CEO"),
                    ("manager", "Manager"),
                    ("worker", "Worker"),
                    ("specialist", "Specialist"),
                    ("pilot", "Aircraft pilot"),
                    ("none", "None"),
                ],
                default="none",
                help_text="Users work job title, model worker in organization app",
                max_length=20,
            ),
        ),
    ]
