version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    hostname: db
    environment:
      - POSTGRES_DB=samdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  app:
    build: .
    container_name: web-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=samdatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
