version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=samdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5433:5432"
    restart: always

  app:
    build: .
    container_name: web-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
     db:
       condition: service_healthy
