# Generated by Django 4.2.2 on 2023-08-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(max_length=200)),
                ("telephone", models.TextField(max_length=100)),
                ("email_domain", models.TextField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("office", "Airport office"),
                            ("control", "Flight control"),
                            ("mechanic", "Aircraft machinery"),
                            ("cleaning", "Aircraft cleaning department"),
                            ("air", "aircraft Crew"),
                            ("IT", "IT department"),
                        ],
                        help_text="Name of department",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="information about department", max_length=200
                    ),
                ),
                (
                    "Airport_ID",
                    models.ForeignKey(
                        help_text="Airport ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airport",
                    ),
                ),
            ],
        ),
    ]
