# Generated by Django 4.2.2 on 2024-02-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of Company", max_length=100)),
                (
                    "address",
                    models.TextField(
                        help_text="Companies head office address", max_length=200
                    ),
                ),
                (
                    "telephone",
                    models.TextField(
                        help_text="Companies contact phone no", max_length=100
                    ),
                ),
                (
                    "email_domain",
                    models.TextField(help_text="Companies email_domina", max_length=50),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Other important information about Company",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Name of worker", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Last name of worker", max_length=50),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("office", "Airport office"),
                            ("control", "Flight control"),
                            ("mechanic", "Aircraft machinery"),
                            ("cleaning", "Aircraft cleaning department"),
                            ("air", "Aircraft Crew"),
                            ("IT", "IT department"),
                            ("external", "External Company"),
                        ],
                        help_text=" Worker department, model department in organization app",
                        max_length=50,
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        choices=[
                            ("ceo", "CEO"),
                            ("manager", "Manager"),
                            ("worker", "Worker"),
                            ("specialist", "Specialist"),
                            ("pilot", "Aircraft pilot"),
                            ("none", "None"),
                            ("admin", "Administrator IT"),
                        ],
                        help_text="Worker  job title, model worker in organization app",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(help_text="Worker address", max_length=100),
                ),
                (
                    "phone_no",
                    models.CharField(help_text="Worker phone no.", max_length=50),
                ),
                (
                    "information",
                    models.TextField(
                        help_text="Information about worker", max_length=50
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("office", "Airport office"),
                            ("control", "Flight control"),
                            ("mechanic", "Aircraft machinery"),
                            ("cleaning", "Aircraft cleaning department"),
                            ("air", "Aircraft Crew"),
                            ("IT", "IT department"),
                            ("external", "External Company"),
                        ],
                        help_text="Name of department",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="information about department", max_length=200
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.company",
                    ),
                ),
            ],
        ),
    ]
