# Generated by Django 4.2.2 on 2023-10-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_alter_company_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Name of worker", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Name of worker", max_length=50),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("office", "Airport office"),
                            ("control", "Flight control"),
                            ("mechanic", "Aircraft machinery"),
                            ("cleaning", "Aircraft cleaning department"),
                            ("air", "aircraft Crew"),
                            ("IT", "IT department"),
                        ],
                        help_text=" Worker department, model department in organization app",
                        max_length=50,
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        choices=[
                            ("ceo", "CEO"),
                            ("manager", "Manager"),
                            ("worker", "Worker"),
                            ("specialist", "Specialist"),
                            ("pilot", "Aircraft pilot"),
                        ],
                        help_text="Worker  job title, model worker in organization app",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.company",
                    ),
                ),
            ],
        ),
    ]
