# Generated by Django 4.2.2 on 2023-10-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="address",
            field=models.CharField(
                default=1, help_text="Worker address", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worker",
            name="information",
            field=models.TextField(
                default=1, help_text="Information about worker", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="worker",
            name="phone_no",
            field=models.CharField(
                default=1, help_text="Worker phone no.", max_length=50
            ),
            preserve_default=False,
        ),
    ]
