# Generated by Django 4.2.2 on 2023-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_worker_address_worker_information_worker_phone_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="company_id",
            new_name="company",
        ),
    ]
