# Generated by Django 4.2.2 on 2024-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_alter_department_name_alter_worker_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="last_name",
            field=models.CharField(help_text="Last name of worker", max_length=50),
        ),
    ]
