# Generated by Django 4.2.2 on 2023-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of offer", max_length=50)),
                ("price", models.FloatField(help_text="Price of offer")),
                ("description", models.TextField(help_text="Description of offer")),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Name of training", max_length=50)),
                ("price", models.FloatField(help_text="Price of training")),
                ("description", models.TextField(help_text="Description of training")),
                (
                    "hours",
                    models.IntegerField(help_text="Number of hours the course takes"),
                ),
            ],
        ),
    ]
