# Generated by Django 4.2.2 on 2023-08-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offer", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="worker_id",
            field=models.ForeignKey(
                help_text="Teachers ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.worker",
            ),
        ),
    ]
