# Generated by Django 4.2.2 on 2023-10-01 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0003_offer_airport_id_training_airport_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offer",
            old_name="airport_id",
            new_name="airport",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="airport_id",
            new_name="airport",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="worker_id",
            new_name="worker",
        ),
    ]
