# Generated by Django 4.2.2 on 2023-10-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_worker"),
        ("offer", "0004_rename_airport_id_offer_airport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="worker",
            field=models.ForeignKey(
                help_text="Teachers ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.worker",
            ),
        ),
    ]
