# Generated by Django 4.2.2 on 2023-10-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_outsideaircraftstand_size"),
        ("airport_facilities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="department_id",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="others",
            old_name="department_id",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="property",
            old_name="department_id",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="department_id",
            new_name="department",
        ),
        migrations.AddField(
            model_name="building",
            name="airport",
            field=models.ForeignKey(
                blank=True,
                help_text="Aiport ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airport",
            ),
        ),
        migrations.AddField(
            model_name="others",
            name="airport",
            field=models.ForeignKey(
                blank=True,
                help_text="Aiport ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airport",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="airport",
            field=models.ForeignKey(
                blank=True,
                help_text="Aiport ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airport",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="airport",
            field=models.ForeignKey(
                blank=True,
                help_text="Aiport ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airport",
            ),
        ),
    ]
