# Generated by Django 4.2.2 on 2024-02-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacture",
                    models.CharField(
                        help_text="Name op aircraft producer", max_length=50
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Aircraft name or no", max_length=50),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("A", "Airplane"),
                            ("H", "Helicopter"),
                            ("AS", "Airship"),
                            ("G", "Glider"),
                            ("P", "Paramotor"),
                            ("B", "Balloon"),
                            ("UAV", "Unmanned Aerial Vehicle"),
                        ],
                        help_text="Type of Aircraft, from list",
                        max_length=3,
                    ),
                ),
                (
                    "take_off_ground",
                    models.IntegerField(
                        help_text="Take off first part, where aircraft is on the ground in meters"
                    ),
                ),
                (
                    "take_off_over_50ft_distance",
                    models.IntegerField(
                        help_text="Take off second part, from where the vehicle leaves the ground to until it reaches 50 ft in meters"
                    ),
                ),
                (
                    "landing_groundroll",
                    models.IntegerField(
                        help_text="aircraft landing distance - on the ground in meters"
                    ),
                ),
                (
                    "fuel_capacity",
                    models.IntegerField(help_text="Aircraft fuel capacity"),
                ),
                (
                    "runway_surface_type",
                    models.CharField(
                        choices=[
                            ("ASP", "Asphalt"),
                            ("BIT", "Bituminous asphalt or tarmac"),
                            ("CLA", "Clay"),
                            ("COM", "Composite"),
                            ("CON", "Concrete"),
                            ("COP", "Composite"),
                            ("COR", "Coral - fine crushed coral reef structures"),
                            ("GRE", "Graded or rolled earth, grass on graded earth"),
                            ("GRS", "Grass or earth not graded or rolled"),
                            ("GVL", "Gravel"),
                            ("ICE", "Ice"),
                            ("LAT", "Laterite"),
                            ("MAC", "Macadam"),
                            (
                                "PEM",
                                "Partially concrete, asphalt or bitumen-bound macadam",
                            ),
                            ("PER", "Permanent surface, details unknown"),
                            (
                                "PSP",
                                "Marston Matting (derived from pierced/perforated steel planking",
                            ),
                            ("SAN", "Sand"),
                            ("SMT", "Sommerfeld Tracking"),
                            ("SNO", "Snow"),
                            ("U", "Unknown surface"),
                            ("WAT", "Water"),
                        ],
                        help_text="Surface that aircraft can land",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Important information about aircraft", max_length=500
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AircraftHangared",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aircraft_registration_no",
                    models.CharField(
                        blank=True,
                        help_text="Registration no",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "airport_property",
                    models.BooleanField(
                        help_text="Information if airport is the owner of this aircraft"
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        help_text="Aircraft ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "airport",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aiport ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airport",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
                (
                    "hangar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hangar ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.hangar",
                    ),
                ),
                (
                    "outside_stand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Outside stand ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.outsideaircraftstand",
                    ),
                ),
            ],
        ),
    ]
