# Generated by Django 4.2.2 on 2023-08-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
        ("aircraft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftHangared",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aircraft_registration_no",
                    models.CharField(
                        blank=True,
                        help_text="Registration no",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "airport_property",
                    models.BooleanField(
                        help_text="Information if airport is the owner of this aircraft"
                    ),
                ),
                (
                    "aircraft_id",
                    models.ForeignKey(
                        help_text="Aircraft ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "hangar_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hangar ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.hangar",
                    ),
                ),
            ],
        ),
    ]
