# Generated by Django 4.2.2 on 2023-08-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airport", "0001_initial"),
        ("aircraft", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircrafthangared",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clients.client"
            ),
        ),
        migrations.AddField(
            model_name="aircrafthangared",
            name="hangar_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Hangar ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.hangar",
            ),
        ),
        migrations.AddField(
            model_name="aircrafthangared",
            name="outside_stand_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Outside stand ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.outsideaircraftstand",
            ),
        ),
    ]
