# Generated by Django 4.2.2 on 2023-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0004_aircrafthangared_airport_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircrafthangared",
            name="airport_id",
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="take_off_ground",
            field=models.IntegerField(
                help_text="Take off first part, where aircraft is on the ground meters"
            ),
        ),
    ]
