# Generated by Django 4.2.2 on 2023-09-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_outsideaircraftstand_size"),
        ("aircraft", "0005_remove_aircrafthangared_airport_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircrafthangared",
            name="airport_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Aiport ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airport",
            ),
        ),
    ]
