# Generated by Django 4.2.2 on 2023-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0007_rename_aircraft_id_aircrafthangared_aircraft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="type",
            field=models.CharField(
                choices=[
                    ("A", "Airplane"),
                    ("H", "Helicopter"),
                    ("AS", "Airship"),
                    ("G", "Glider"),
                    ("P", "Paramotor"),
                    ("B", "Balloon"),
                    ("UAV", "Unmanned Aerial Vehicle"),
                ],
                help_text="Type of Aircraft, from list",
                max_length=50,
            ),
        ),
    ]
