# Generated by Django 4.2.2 on 2024-02-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corporate_client",
                    models.BooleanField(
                        blank=True, help_text="If client is a corporate - Yes/No"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Name of client", max_length=20, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name of client",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pesel",
                    models.IntegerField(
                        blank=True, help_text=" Pesel of client", null=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="If client is a company, name of company",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nip",
                    models.IntegerField(
                        blank=True,
                        help_text="If client is a company, NIP of company",
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        help_text="Email of client",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone_no", models.IntegerField(help_text="Phone no. of client")),
                (
                    "aeroclub_meber",
                    models.BooleanField(
                        help_text="Information if client is a Aeroclub member"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company ID - information which organization client is it",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="organization.company",
                    ),
                ),
                (
                    "offer",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If client uses the offer, offer name",
                        to="offer.offer",
                    ),
                ),
                (
                    "training",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If client was on training, training name",
                        to="offer.training",
                    ),
                ),
            ],
        ),
    ]
