# Generated by Django 4.2.2 on 2023-08-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airport", "0001_initial"),
        ("offer", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="offer",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client uses the offer, offer name",
                null=True,
                to="offer.offer",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="training",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client was on training, training name",
                null=True,
                to="offer.training",
            ),
        ),
        migrations.AddField(
            model_name="aeroclubmember",
            name="airport_id",
            field=models.ForeignKey(
                help_text="Airport ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airport",
            ),
        ),
    ]
