# Generated by Django 4.2.2 on 2023-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("offer", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="offer",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client uses the offer, offer name",
                to="offer.offer",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="training",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client was on training, training name",
                to="offer.training",
            ),
        ),
    ]
