# Generated by Django 4.2.2 on 2023-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0003_offer_airport_id_training_airport_id"),
        ("clients", "0003_client_corporate_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="offer",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client uses the offer, offer name",
                null=True,
                to="offer.offer",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="training",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client was on training, training name",
                null=True,
                to="offer.training",
            ),
        ),
    ]
