# Generated by Django 4.2.2 on 2023-10-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0005_alter_training_worker"),
        ("clients", "0005_client_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="offer",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client uses the offer, offer name",
                to="offer.offer",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="training",
            field=models.ManyToManyField(
                blank=True,
                help_text="If client was on training, training name",
                to="offer.training",
            ),
        ),
    ]
