# Generated by Django 4.2.2 on 2023-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_alter_client_offer_alter_client_training"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="company_id",
            new_name="company",
        ),
    ]
