# Generated by Django 4.2.2 on 2023-11-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_rename_company_id_department_company"),
        ("clients", "0007_rename_company_id_client_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                help_text="Company ID - information which organization client is it",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="organization.company",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.CharField(
                blank=True, help_text="Email of client", max_length=50, null=True
            ),
        ),
    ]
