# Generated by Django 4.2.2 on 2023-08-16 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=100),
                ),
                ("content", models.TextField(help_text="Main information ")),
                (
                    "date_posted",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 8, 16, 8, 52, 51, 7709, tzinfo=datetime.timezone.utc
                        ),
                        help_text="Date post",
                    ),
                ),
                (
                    "view_date",
                    models.DateTimeField(
                        help_text="date when notification will appear on dashboard"
                    ),
                ),
            ],
        ),
    ]
