# Generated by Django 4.2.2 on 2024-02-19 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=100),
                ),
                ("content", models.TextField(help_text="Main information ")),
                (
                    "date_posted",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Date post"
                    ),
                ),
                (
                    "view_date",
                    models.DateField(
                        help_text="date when notification will appear on dashboard"
                    ),
                ),
                (
                    "airport",
                    models.ForeignKey(
                        help_text="Airport ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport.airport",
                    ),
                ),
            ],
        ),
    ]
