# Generated by Django 4.2.2 on 2023-08-20 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 20, 9, 46, 30, 953465, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
