# Generated by Django 4.2.2 on 2023-08-25 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 25, 8, 52, 35, 415633, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="view_date",
            field=models.DateField(
                help_text="date when notification will appear on dashboard"
            ),
        ),
    ]
