# Generated by Django 4.2.2 on 2023-08-27 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_alter_notification_date_posted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 27, 16, 51, 54, 42422, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
