# Generated by Django 4.2.2 on 2023-08-28 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 28, 7, 2, 41, 513291, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
