# Generated by Django 4.2.2 on 2023-08-31 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0011_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 31, 7, 58, 14, 922042, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
