# Generated by Django 4.2.2 on 2023-09-10 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 10, 9, 49, 13, 356378, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
