# Generated by Django 4.2.2 on 2023-09-11 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0014_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 11, 18, 13, 15, 579328, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
