# Generated by Django 4.2.2 on 2023-10-01 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0022_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 1, 15, 45, 37, 275756, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
