# Generated by Django 4.2.2 on 2023-10-01 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0023_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 1, 16, 50, 0, 667386, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
