# Generated by Django 4.2.2 on 2023-10-07 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0024_alter_notification_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 7, 16, 37, 18, 509823, tzinfo=datetime.timezone.utc
                ),
                help_text="Date post",
            ),
        ),
    ]
